version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ./wait-for-it.sh db:3306 --timeout=30 --strict -- python main.py
  db:
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: jphacks
      MYSQL_DATABASE: test
    # TODO: persist database
    # volumes:
    #     - ./data/mysql:/var/lib/mysql
