name: Type Check

on:
  push:
    paths:
      - '**/*.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy src/ --ignore-missing-imports
