name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**/*'
      - 'health-chaireFW/**/*'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SERVER_APP_DIR }}
            git pull origin main
            docker compose down
            docker compose up -d --build
